; Tema: One Dark
; Podes editar as cores em formato hexadecimal #RRGGBB

[meta]
name    = One Dark

[colors]
bg      = #282c34
bg2     = #21252b
bg3     = #2c313c
bg4     = #3e4451
fg      = #abb2bf
fg2     = #828997
fg3     = #5c6370
accent  = #c678dd
green   = #98c379
red     = #e06c75
yellow  = #e5c07b
blue    = #61afef
cyan    = #56b6c2
orange  = #d19a66
bg_row  = #21252b
