; Tema: Nord
; Podes editar as cores em formato hexadecimal #RRGGBB

[meta]
name    = Nord

[colors]
bg      = #2e3440
bg2     = #242933
bg3     = #3b4252
bg4     = #434c5e
fg      = #eceff4
fg2     = #d8dee9
fg3     = #4c566a
accent  = #88c0d0
green   = #a3be8c
red     = #bf616a
yellow  = #ebcb8b
blue    = #81a1c1
cyan    = #8fbcbb
orange  = #d08770
bg_row  = #232830
