; Tema: Monokai
; Podes editar as cores em formato hexadecimal #RRGGBB

[meta]
name    = Monokai

[colors]
bg      = #272822
bg2     = #1e1f1c
bg3     = #3e3d32
bg4     = #49483e
fg      = #f8f8f2
fg2     = #cfcfc2
fg3     = #75715e
accent  = #a6e22e
green   = #a6e22e
red     = #f92672
yellow  = #e6db74
blue    = #66d9ef
cyan    = #66d9ef
orange  = #fd971f
bg_row  = #1e1f1c
