; Tema: Catppuccin Mocha
; Podes editar as cores em formato hexadecimal #RRGGBB

[meta]
name    = Catppuccin Mocha

[colors]
bg      = #1e1e2e
bg2     = #181825
bg3     = #313244
bg4     = #45475a
fg      = #cdd6f4
fg2     = #a6adc8
fg3     = #6c7086
accent  = #cba6f7
green   = #a6e3a1
red     = #f38ba8
yellow  = #f9e2af
blue    = #89b4fa
cyan    = #89dceb
orange  = #fab387
bg_row  = #202030
