; Tema: Tokyo Night
; Podes editar as cores em formato hexadecimal #RRGGBB

[meta]
name    = Tokyo Night

[colors]
bg      = #1a1b2e
bg2     = #13141f
bg3     = #24283b
bg4     = #414868
fg      = #a9b1d6
fg2     = #787c99
fg3     = #565f89
accent  = #bb9af7
green   = #9ece6a
red     = #f7768e
yellow  = #e0af68
blue    = #7aa2f7
cyan    = #7dcfff
orange  = #ff9e64
bg_row  = #16172a
